version: '3.3'

services:
    # === airflow ===========================================================
    # based on https://github.com/shamoji-tech/airflow_docker
    airflow_postgres:
        image: postgres:9.6
        container_name: postgres
        env_file:
            - .env
        volumes:
            # === linux
            # - ./postgres/pgdata:/var/lib/postgresql/data/pgdata
            # === windows
            - ./postgres/pgdata:/var/lib/postgresql/data

    init:
        image: "apache/airflow:1.10.10-python3.7"
        container_name: airflow_initializer
        env_file:
            - .env
        depends_on:
            - airflow_postgres
        command: initdb
