{
 "title": "FGB NMS Early Alert",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Locations",
    "label": "Satellite Time Series Extraction Locations",
    "query": "SHOW TAG VALUES FROM moda_ABI WITH KEY=location"
   },
   { "name": "metric", "label": "Time Series Metric", "query": "SHOW FIELD KEYS" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 0 },
   "content": "![map of sub-regions](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fgbnms/static_files/FGBdb_map_2021.png)"
  },
  {
   "title": "Welcome to the Flower Garden Banks data dashboard",
   "type": "text",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 0 },
   "content": "![logo image](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fgbnms/static_files/FGB_DBv2_logos_banner2.png)\n\n### NEW: A real-time Sofar Buoy is now installed at East Flower Garden Bank. Please click [HERE](https://spotters.sofarocean.com/?spotter-filter=SPOT-30987C) to access data.\n\n\nDirections for site navigation:\n\nSelect location(s) for satellite time series extraction using the \"Locations\" menu at left.\n\nSelect location(s) for buoy data using the \"Buoys\" menu at left.\n\nDisplay mean, climatology, or anomalies of extracted satellite data using the \"Time Series Metric\" menu at left.\n\nThe range of the displayed time period can be adjusted at top right.\n\nScroll down to see all image and time series data panels.\nTo show or hide a panel, simply click on the panel title\n\nLocations of extracted data:\n* A: Stetson Bank\n* B: West Flower Garden Bank\n* C: Horseshoe Bank\n* D: East Flower Garden Bank\n* E: MacNeil Bank\n* F: Rankin/28 Fathom Bank\n* G: Bright Bank\n* H: Geyer Bank\n* I: Elvers Bank\n* J: McGrail Bank\n* K: Bouma Bank\n* L: Rezak Bank\n* M: Sidner Bank\n* N: Parker Bank\n* O: Alderice Bank\n* P: Sonnier Bank\n* COAST 1-4: Coastal Regions of Interest\n* SS 1-8: Sentinel Sites\n \n\n\n\n"
  },
  { "title": "Satellite Imagery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "MODIS-Aqua CHLa 7-Day anomaly images (mg/m^3)",
   "type": "erddap-panel",
   "description": "MODIS-Aqua 1km chlor_a product (mg/m^3) binned to 7-day intervals.\nAnomaly images created by subtracting 7-day climatologies made using data from 2003-2019.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "MODIS-Aqua 7-Day nightime SST anomaly images (DegC)",
   "type": "erddap-panel",
   "description": "MODIS-Aqua 1km nighttime SST product (DegC) binned to 7-day intervals.\nAnomaly images created by subtracting 7-day climatologies made using data from 2003-2019.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "MODIS-Aqua remote sensing reflectance at 667nm (susp. sediment proxy) 7-Day anomaly images (sr^-1)",
   "type": "erddap-panel",
   "description": "MODIS-Aqua 1km Rrs_667 (sr^-1) binned to 7-day intervals.\nThis product is a proxy for suspended sediments in surface waters.\nAnomaly images created by subtracting 7-day climatologies made using data from 2003-2019.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "MODIS-Aqua ABI (Algal Bloom Index) 7-Day anomaly images (W/m^2/um/sr)",
   "type": "erddap-panel",
   "description": "MODIS-Aqua 1km Algal Bloom Index (ABI) product (W m^2 um^-1 sr^-1) binned to 7-day intervals. ABI is based on normalized fluorescent line height and is normalized by green reflectance to account for suspended sediments. \nAnomaly images created by subtracting 7-day climatologies made using data from 2003-2019.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 }
  },
  {
   "title": "Satellite Imagery Time Series Extractions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }
  },
  {
   "title": "MODIS Chlorophyll-a $metric @ $Locations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modis_abi",
     "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"moda_chlor_a\"\nWHERE (\"location\" =~ /^$Locations$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "MODIS nightime SST $metric @ $Locations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modis_abi",
     "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"moda_sst4\"\nWHERE (\"location\" =~ /^$Locations$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "MODIS Rrs 667 (susp. sediment proxy) $metric @ $Locations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modis_abi",
     "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"moda_Rrs_667\"\nWHERE (\"location\" =~ /^$Locations$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "MODIS ABI (Algal Bloom Index) $metric @ $Locations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modis_abi",
     "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"moda_ABI\"\nWHERE (\"location\" =~ /^$Locations$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  { "title": "River Discharge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Discharge from Texas rivers $metric (combined discharge from guages shown as  green circles on map)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(/^$metric$/)  FROM \"river_discharge\"\nWHERE (\"location\" = 'FGBdb_TX') AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Discharge from Mississippi River $metric (discharge from guage shown by red circle on map)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TX $metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "river_discharge",
     "query": "SELECT mean(/^$metric$/)  FROM \"river_discharge\"\nWHERE (\"location\" = 'FGBdb_MS') AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "$metric" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "FGBdb_MS" }
     ]
    }
   ]
  },
  { "title": "More Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Data Sources and Contact Information",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "content": "* Satellite data is from the Moderate Resolution Imaging Spectroradiometer (MODIS-Aqua) sensor and is obtained from the [Ocean Biology Processing Group](https://oceancolor.gsfc.nasa.gov/) at NASA's Goddard Space Flight Center.\n\n* Algal Bloom Index (ABI) is calculated using the method of Hu and Feng (2016; doi: 10.1117/1.JRS.11.012003) \n\n* River discharge data is obtained from the [USGS National Water Information System](https://waterdata.usgs.gov/nwis). Discharge values from the Colorado, Brazos, Trinity, Neches and Sabine Rivers (green circles on map above) are summed for discharge into the northwest Gulf of Mexico and plotted above. Discharge data from the Mississippi River (yellow circle on map above) is also plotted.\n\nPlease feel free to contact us with questions or to sign up for email alerts:\n\nDr. Daniel Otis - [dotis@usf.edu](mailto:dotis@usf.edu)\n\n"
  },
  {
   "title": "This work supported by",
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 82 },
   "content": "![logo image](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fgbnms/static_files/FGB_DBv2_logos_banner2.png)"
  }
 ]
}