{
 "title": "FWC Coral Disease Dash",
 "time": { "from": "now-3y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Locations",
    "query": "SHOW TAG VALUES FROM \"chlor_a\" WITH KEY = \"location\" WHERE \"region\" = 'FWC'"
   },
   {
    "name": "Buoys",
    "query": "SHOW TAG VALUES FROM \"salinity\" WITH KEY = \"location\""
   },
   { "name": "metric", "query": "SHOW FIELD KEYS from chlor_a" },
   {
    "name": "USGS_Gauges",
    "label": "USGS Gauges",
    "query": "SHOW TAG VALUES FROM disch WITH KEY=location WHERE \"region\"='FWC'"
   }
  ]
 },
 "panels": [
  {
   "title": "Introduction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "![map of sub-regions](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fwc/static_files/FWC_DBv24_map.png)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Welcome to the FDEP/FWC Coral Disease Dashboard",
   "type": "text",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "![logo image](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fwc/static_files/FWC_DB_logos_vNew.png)\n\n\n* Select location(s) for satellite time series  extraction using the \"Locations\" menu at left.\n* Select location(s) for buoy data using the \"Buoys\" menu at left.\n* Display mean, climatology, or anomalies of extracted satellite data using the \"metric\" menu at left.\n* The range of the displayed time period can be adjusted at top right.\n* Scroll down to see all image and time series data panels.\n* **To show or hide a panel, simply click on the panel title**\n* More detailed information on data products and links to download data is at bottom.\n\n------------------------------------------------------------------------\n\nTo see more detail in Biscayne Bay and Florida's Coral Reef, dashboards with zoomed in satellite images are available:\n\n\n* [Biscayne Bay and Southeast Florida](/d/RRa51qeGz/biscayne-bay-and-southeast-florida-drilldown)\n* [Florida's Coral Reef](/d/k7kraqeMk/keys-reef-tract-drilldown)\n\n------------------------------------------------------------------------\n\n### Scroll down for locations of extracted data:\n|     |                          |\n|-----| -------------------------|\n| SLI | St. Lucie River inlet    \n| PBI | Palm Beach inlet\n| PEV | Port Everglades\n| MIA | Miami\n| MOL | Molasses Reef\n| SOM | Sombrero Key\n| SUG | Sugarloaf Key\n| KW  | Key West\n\n------------------------------------------------------------------------\n\n### Buoy Locations:\n1. Whipray Basin\n2. Butternut Key\n3. Peterson Key\n4. Bob Allen Keys\n5. Little Rabbit Key\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Satellite Imagery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "VIIRS-SNPP CHLa 7-Day anomaly images (mg/m^3)",
     "type": "imars-grafanaerddap-panel",
     "description": "VIIRS-SNPP 750-m chlorophyll-a concentration (mg/m^3) binned to 7-day intervals. Anomaly images are created by subtracting a 7-day climatology using data from 2013-2019.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 }
    },
    {
     "title": "VIIRS-SNPP 7-Day nighttime SST anomaly images (DegC)",
     "type": "imars-grafanaerddap-panel",
     "description": "VIIRS-SNPP 750-m nighttime sea-surface temperature (DegC) binned to 7-day intervals. Anomaly images are created by subtracting a 7-day climatology using data from 2013-2019.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 }
    },
    {
     "title": "VIIRS-SNPP remote sensing reflectance at 671nm 7-Day anomaly images (sr^-1)",
     "type": "imars-grafanaerddap-panel",
     "description": "VIIRS-SNPP 750-m remote sensing reflectance (sr^-1) at 671nm binned to 7-day intervals. This is a proxy for suspended sediments at the surface. Anomaly images are created by subtracting a 7-day climatology using data from 2013-2019.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 }
    },
    {
     "title": "VIIRS Diffuse Attenuation Coefficient at 490nm (Kd490) 7-day Anomaly Images (water clarity proxy)",
     "type": "imars-grafanaerddap-panel",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 }
    }
   ]
  },
  {
   "title": "Stony Coral Tissue Loss Disease (SCTLD) Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SCTLD Advance",
     "type": "text",
     "gridPos": { "h": 17, "w": 9, "x": 0, "y": 19 },
     "options": {
      "content": "* The animation at right shows the advance of Stony Coral Tissue Loss Disease (SCTLD) based on the model of Muller et al. (2020) alongside the field observations from FWC's CREMP and SECREMP programs.\n\n* SCTLD was first observed near Virginia Key in September 2014 and then spread to both the north and south.\n\n* Annual observations of SCTLD by [FWC's CREMP and SECREMP programs](https://myfwc.com/research/habitat/coral/cremp/) are shown in the map panel below.\n\n\n\n**References:**\n\n* Muller, E.M., Sartor, C., Alcaraz, N.I., and van Woesik, R. Spatial Epidemiology of the Stony-Coral-Tissue-Loss-Disease in Florida. Front. Mar. Sci. 2020. doi: 10.3389/fmars.2020.00163\n\n* Precht, W.F., Gintert, B.E., Robbart, M.L., Fura, R, and van Woesik, R. Unprecedented disease-related coral mortality in Southeastern Florida. Sci. Rep. 6: 31374. 2016.\ndoi: 10.1038/srep31374\n\n\n\n"
     }
    },
    {
     "title": "Animated map of SCTLD advance",
     "type": "text",
     "gridPos": { "h": 17, "w": 10, "x": 9, "y": 19 },
     "options": {
      "content": "\n![FK_SCTLD_advance_images.gif](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fwc/static_files/FK_SCTLD_advance_images.gif)\n\n\n\n"
     }
    },
    {
     "title": "Observations of Stony Coral Tissue Loss Disease",
     "type": "text",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 36 },
     "content": "<a \n  href=\"https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fwc/static_files/SCTLD_panel_vDB21.png\"\n><img \n  src=\"https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fwc/static_files/SCTLD_panel_vDB21.png\"\n></img>\n</a>"
    }
   ]
  },
  {
   "title": "Satellite Imagery Time Series Extractions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Nighttime SST $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"sstn\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /VSNPP/)  AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "VIIRS Rrs 671 $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"Rrs_671\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /VSNPP/)  AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "Chlorophyll-a $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) as metric FROM \"chlor_a\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /VSNPP/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "VIIRS Kd_490 (water clarity proxy) $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"Kd_490\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /VSNPP/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "MODIS ABI $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"ABI\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /MODA/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "River Discharge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "USGS Gage Height from Tamiami Canal draining into Biscayne Bay (red circle on map - meters)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$tag_location $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "river_discharge",
       "query": "SELECT /^$metric$/ FROM disch\nWHERE (\"location\" =~ /^$USGS_Gauges$/ AND $timeFilter)\nGROUP BY \"location\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Buoy Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "In-situ salinity (psu) at ~1m depth from selected buoy(s)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "river_discharge",
       "query": "SELECT sea_water_practical_salinity as sea_water_practical_salinity FROM \"salinity\"\nWHERE (\"location\" =~ /^$Buoys$/) AND $timeFilter AND sea_water_practical_salinity > -999\nGROUP BY \"location\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "In-situ temperature at ~1m depth (psu) from selected buoy(s)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "river_discharge",
       "query": "SELECT sea_water_temperature as sea_water_temperature FROM \"salinity\"\nWHERE (\"location\" =~ /^$Buoys$/) AND $timeFilter AND sea_water_temperature > -999\nGROUP BY \"location\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "More Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data Sources and contact information",
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "* Satellite data is from the Moderate Resolution Imaging Spectroradiometer (MODIS-Aqua) sensor and the Visible Infrared Imaging Spectrometer Suite (VIIRS). All satellite products are  obtained from the [Ocean Biology Processing Group](https://oceancolor.gsfc.nasa.gov/) at NASA's Goddard Space Flight Center.\n\n* Algal Bloom Index (ABI) is calculated using the method of Hu and Feng (2016; doi: 10.1117/1.JRS.11.012003) \n\n* River discharge and gage height data (green dots) are obtained from the [USGS National Water Information System](https://waterdata.usgs.gov/nwis). Gage height from the C-8 Canal is used to estimate discharge from creeks and canals draining into Biscayne Bay. Discharge values from the Shark, Broad, Lostman's and Chatham Rivers are summed to estimate discharge into Florida Bay shown on plot above. The St. Lucie River is influenced by controlled discharges from Lake Okeechobee and is shown separately. \n\n* Buoys in Florida Bay are operated by the National Park Service and data are obtained from the [National Data Buoy Center.](https://www.ndbc.noaa.gov/) \n\n* Coral Disease observations were made by the [FWC's Coral Reef Evaluation and Monitoring Project (CREMP)](https://myfwc.com/research/habitat/coral/cremp/). The spatio-temporal model of disease advance is from Muller et al. (2020; doi:10.3389/fmars.2020.00163).\n\n* Satellite images can be accessed and visualized using ERDDAP's user interface. Satellite datasets for this project are currently hosted on [USF IMaRS's ERDDAP server](http://131.247.136.200:8080/erddap/info/index.html?page=1&itemsPerPage=1000).\n\nPlease feel free to contact us with questions or to sign up for email alerts:\n\nDr. Dan Otis - [dotis@usf.edu](mailto:dotis@mail.usf.edu)\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "This work supported by",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "options": {
    "content": "![logo image](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fwc/static_files/FWC_DB_logos_vNew.png)\n"
   },
   "targets": [
    {}
   ]
  }
 ]
}