{
 "title": "Keys Reef Tract Drilldown",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   { "name": "Locations", "query": "SLI,PBI,PEV,MIA,MOL,SOM,SUG,KW" },
   {
    "name": "Bouys",
    "query": "BOBALLEN,BUTTERNUT,LITTLERABBIT,PETERSON,WHIPRAY"
   },
   { "name": "metric", "query": "SHOW FIELD KEYS" }
  ]
 },
 "panels": [
  {
   "title": "Introduction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 21, "w": 12, "x": 0, "y": 1 },
     "content": "![map of sub-regions](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fwc/static_files/FWC_DBv24_map.png)"
    },
    {
     "title": "Welcome to the FDEP/FWC Coral Disease Dashboard",
     "type": "text",
     "gridPos": { "h": 21, "w": 12, "x": 12, "y": 1 },
     "content": "![logo image](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fwc/static_files/FWC_DB_logos_vNew.png)\n\nSelect location(s) for satellite time series  extraction using the \"Locations\" menu at left.\n\nSelect location(s) for buoy data using the \"Buoys\" menu at left.\n\nDisplay mean, climatology, or anomalies of extracted satellite data using the \"metric\" menu at left.\n\nThe range of the displayed time period can be adjusted at top right.\n\nScroll down to see all image and time series panels.\n\nMore detailed information on data products and links to download data is at bottom.\n\nLocations of extracted data:\n* SLI: St. Lucie River inlet\n* PBI: Palm Beach inlet\n* PEV: Port Everglades\n* MIA: Miami\n* MOL: Molasses Reef\n* SOM: Sombrero Key\n* SUG: Sugarloaf Key\n* KW: Key West\n\nBuoy Locations:\n* 1: Whipray Basin\n* 2: Butternut Key\n* 3: Peterson Key\n* 4: Bob Allen Keys\n* 5: Little Rabbit Key"
    }
   ]
  },
  { "title": "Satellite Imagery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "VIIRS Chlorophyll-a 7-day Anomaly Images",
   "type": "erddap-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "VIIRS nighttime SST 7-day Anomaly Images",
   "type": "erddap-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "MODIS-Aqua Algal Bloom Index 7-Day Anomaly Images (W/m^2/um/sr)",
   "type": "erddap-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "VIIRS Reflectance at 671nm 7-day Anomaly Images (turbidity proxy)",
   "type": "erddap-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "VIIRS Diffuse Attenuation Coefficient at 490nm (Kd490) 7-day Anomaly Images (water clarity proxy)",
   "type": "erddap-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Stony Coral Tissue Loss Disease (SCTLD) Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "SCTLD Progression",
     "type": "text",
     "gridPos": { "h": 22, "w": 5, "x": 0, "y": 24 },
     "content": "These plots show the advance of SCTLD based on the model of Muller et al. (2020) alongside the field observations from FWC's CREMP and SECREMP programs.\n\n\n"
    },
    {
     "title": "Plot of the advance of SCTLD",
     "type": "text",
     "gridPos": { "h": 22, "w": 7, "x": 5, "y": 24 },
     "content": "![FK_SCTLD_advance_plot.gif](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fwc/static_files/FK_SCTLD_advance_plot.gif)\n\n\n\n"
    },
    {
     "title": "Advanced of SCTLD animated map",
     "type": "text",
     "gridPos": { "h": 22, "w": 11, "x": 12, "y": 24 },
     "content": "\n![FK_SCTLD_advance_images.gif](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fwc/static_files/FK_SCTLD_advance_images.gif)\n\n\n\n"
    },
    {
     "title": "Observations of Stony Coral Tissue Loss Disease",
     "type": "text",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 46 },
     "content": "<a \n  href=\"https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fwc/static_files/SCTLD_panel_vDB21.png\"\n><img \n  src=\"https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fwc/static_files/SCTLD_panel_vDB21.png\"\n></img>\n</a>"
    }
   ]
  },
  {
   "title": "Satellite Imagery Time Series Extractions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "VIIRS SSTN $metric @ $Locations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modis_abi",
     "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"vsnpp_sst\"\nWHERE (\"location\" =~ /^$Locations$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "VIIRS Chlorophyll-a $metric @ $Locations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modis_abi",
     "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"vsnpp_chlor_a\"\nWHERE (\"location\" =~ /^$Locations$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "MODIS ABI $metric @ $Locations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modis_abi",
     "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"moda_ABI\"\nWHERE (\"location\" =~ /^$Locations$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "VIIRS Rrs 671 $metric @ $Locations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modis_abi",
     "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"vsnpp_Rrs_671\"\nWHERE (\"location\" =~ /^$Locations$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "VIIRS Kd_490 (water clarity proxy) $metric @ $Locations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modis_abi",
     "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"vsnpp_Kd_490\"\nWHERE (\"location\" =~ /^$Locations$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "River Discharge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "USGS Gage Height from creeks and canals draining into Biscayne Bay (sum of gage height from rivers shown by red circles on map - meters)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "river_discharge",
       "query": "SELECT mean(/^$metric$/) AS mean FROM \"river_discharge\"\nWHERE (\"location\" = 'FWCdb_EFL') AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "USGS River Discharge from rivers draining to Everglades (sum of discharge from green dots on map - m^3/sec)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "river_discharge",
       "query": "SELECT mean(/^$metric$/) AS mean FROM \"river_discharge\"\nWHERE (\"location\" = 'FKdb') AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "St Lucie River Discharge (Gage Height - m)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "river_discharge",
       "query": "SELECT mean(/^$metric$/) AS mean FROM \"river_discharge\"\nWHERE (\"location\" = 'FWCdb_STL') AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Buoy Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "In-situ salinity (psu) at ~1m depth from selected buoy(s)",
     "type": "graph",
     "description": "TODO: add other bouys to overview map?",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "river_discharge",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"bouy_sal\"\nWHERE (\"location\" =~ /^$Bouys$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "In-situ temperature at ~1m depth (psu) from selected buoy(s)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "river_discharge",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"bouy_temp\"\nWHERE (\"location\" =~ /^$Bouys$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "More Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Data Sources and contact information",
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "content": "* Satellite data is from the Moderate Resolution Imaging Spectroradiometer (MODIS-Aqua) sensor and the Visible Infrared Imaging Spectrometer Suite (VIIRS). All satellite products are  obtained from the [Ocean Biology Processing Group](https://oceancolor.gsfc.nasa.gov/) at NASA's Goddard Space Flight Center.\n\n* Algal Bloom Index (ABI) is calculated using the method of Hu and Feng (2016; doi: 10.1117/1.JRS.11.012003) \n\n* River discharge and gage height data (green dots) are obtained from the [USGS National Water Information System](https://waterdata.usgs.gov/nwis). Gage height from the C-8 Canal is used to estimate discharge from creeks and canals draining into Biscayne Bay. Discharge values from the Shark, Broad, Lostman's and Chatham Rivers are summed to estimate discharge into Florida Bay shown on plot above. The St. Lucie River is influenced by controlled discharges from Lake Okeechobee and is shown separately. \n\n* Buoys in Florida Bay are operated by the National Park Service and data are obtained from the [National Data Buoy Center.](https://www.ndbc.noaa.gov/) \n\n* Coral Disease observations were made by the [FWC's Coral Reef Evaluation and Monitoring Project (CREMP)](https://myfwc.com/research/habitat/coral/cremp/). The spatio-temporal model of disease advance is from Muller et al. (2020; doi:10.3389/fmars.2020.00163).\n\n* Satellite images can be accessed and visualized using ERDDAP's user interface. Satellite datasets for this project are currently hosted on [USF IMaRS's ERDDAP server](http://131.247.136.200:8080/erddap/info/index.html?page=1&itemsPerPage=1000).\n\nPlease feel free to contact us with questions or to sign up for email alerts:\n\nDr. Dan Otis - [dotis@usf.edu](mailto:dotis@mail.usf.edu)\n\n"
  },
  {
   "title": "This work supported by",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "content": "![logo image](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-fwc/static_files/FWC_DB_logos_vNew.png)\n"
  }
 ]
}