{
 "title": "FK NMS Early Alert",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Locations",
    "label": "Satellite Time Series Extraction Locations",
    "query": "SHOW TAG VALUES FROM \"chlor_a\" WITH KEY = \"location\" WHERE \"region\" = 'FKNMS'"
   },
   { "name": "metric", "label": "Time Series Metric", "query": "SHOW FIELD KEYS from chlor_a" },
   {
    "name": "Buoy",
    "label": "Buoy Locations",
    "query": "SHOW TAG VALUES FROM \"ndbc_buoy\" WITH KEY = \"location\""
   },
   {
    "name": "gauge_locations",
    "label": "Gauge Locations",
    "query": "SHOW TAG VALUES FROM disch WITH KEY=location WHERE \"region\"='FK'"
   }
  ]
 },
 "panels": [
  {
   "title": "Welcome to the Florida Keys Data Dashboard",
   "type": "geomap",
   "description": "This dashboard serves satellite and in-situ data from the Florida Keys National Marine Sanctuary and surrounding areas.",
   "gridPos": { "h": 18, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "url": "mbon-dashboards.marine.usf.edu/static_files/FKdb_River_locs.csv",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "url": "mbon-dashboards.marine.usf.edu/static_files/FKdb_Buoy_locs.csv",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "url": "mbon-dashboards.marine.usf.edu/static_files/FKdb_AOI_labels.csv",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 18, "w": 11, "x": 13, "y": 0 },
   "options": {
    "content": "### Directions for site navigation \n\n\n#### Use mouse to zoom or pan map. Hover over features for more information.\n\n#### Time range displayed can be adjusted at top right.\n\n#### To view time series panels, simply click on the panel title below (e.g. \"Satellite Imagery\")\n\n#### Use dropdown menus above to select:\n - Areas of Interest (AOIs) where time series of satellite data are extracted (black polygons).\n - Time series metric to display (mean, climatology, anomaly).\n - NPS temperature/salinity buoys (blue circles).\n - USGS river discharge gauges (green circles). \n\nFlorida Keys National Marine Sanctuary boundary is shown as a red polygon.\n\nDepth contours are indicated by gray lines.\n\n### Locations of extracted satellite data:\n* BIS: Offshore Biscayne Bay\n* UK: Upper Keys\n* M/UK: Middle/Upper Keys\n* MK: Middle Keys\n* LK: Lower Keys\n* MQ: Marquesas\n* DT: Dry Tortugas\n* WFS: West Florida Shelf\n* SR: Shark River\n* WFB: West Florida Bay\n* EFB: East Florida Bay (SST only)\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Satellite Imagery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "VIIRS-SNPP CHLa 7-Day anomaly images (mg/m^3)",
     "type": "imars-grafanaerddap-panel",
     "description": "VIIRS-SNPP 750-m chlorophyll-a concentration (mg/m^3) binned to 7-day intervals. Anomaly images are created by subtracting a 7-day climatology using data from 2013-2019.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 }
    },
    {
     "title": "VIIRS-SNPP 7-Day nighttime SST anomaly images (DegC)",
     "type": "imars-grafanaerddap-panel",
     "description": "VIIRS-SNPP 750-m nighttime sea-surface temperature (DegC) binned to 7-day intervals. Anomaly images are created by subtracting a 7-day climatology using data from 2013-2019.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 }
    },
    {
     "title": "VIIRS-SNPP remote sensing reflectance at 671nm 7-Day anomaly images (sr^-1)",
     "type": "imars-grafanaerddap-panel",
     "description": "VIIRS-SNPP 750-m remote sensing reflectance (sr^-1) at 671nm binned to 7-day intervals. This is a proxy for suspended sediments at the surface. Anomaly images are created by subtracting a 7-day climatology using data from 2013-2019.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 }
    },
    {
     "title": "MODIS-Aqua Algal Bloom Index (ABI) 7-Day anomaly images (mW cm^-2 um^-1 sr^-1)",
     "type": "imars-grafanaerddap-panel",
     "description": "MODIS-Aqua 1-km Algal Bloom Index (mW cm^-2 um^-1 sr^-1) binned to 7-day intervals. This product can be used to identify algal blooms. Anomaly images are created by subtracting a 7-day climatology using data from 2003-2019.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 }
    },
    {
     "title": "Dynamic biogeographic seascapes (class)",
     "type": "imars-grafanaerddap-panel",
     "description": "Dynamic seascapes are classified using multivariate data and describe basin and gyre scale features and seasonal boundary shifts. A description of seascape classes can be found HERE.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 }
    }
   ]
  },
  {
   "title": "Satellite Imagery Time Series Extractions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "VSNPP Chlorophyll-a $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) as metric FROM \"chlor_a\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /VSNPP/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "VSNPP Nighttime SST $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"sstn\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /VSNPP/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "VIIRS Rrs 671 $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"Rrs_671\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /VSNPP/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "VIIRS Kd_490 $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"Kd_490\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /VSNPP/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "MODIS ABI $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"ABI\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /MODA/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "River Discharge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "USGS River Discharge [ m^3/sec]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$tag_location $col",
       "query": "SELECT /^$metric$/  FROM disch\nWHERE (location =~ /^$gauge_locations$/)\nGROUP BY \"location\"\nfill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "Buoy Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "In-situ temperature at ~1m depth (psu) from $Buoy",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "river_discharge",
       "query": "SELECT mean(\"sea_water_temperature\")\nFROM \"ndbc_buoy\"\nWHERE (\"location\" =~ /^$Buoy$/) AND $timeFilter\nGROUP BY time($__interval), \"location\" fill(null)\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "In-situ salinity (psu) at ~1m depth from $Buoy",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "river_discharge",
       "query": "SELECT mean(\"sea_water_practical_salinity\")\nFROM \"ndbc_buoy\"\nWHERE (\"location\" =~ /^$Buoy$/) AND $timeFilter\nGROUP BY time($__interval), \"location\" fill(null)\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "More Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data Sources and Contact Information",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "* Satellite data (Chlorophyll-a, SST and Rrs_667) is from the Visible Infrared Imaging Spectrometer Suite (VIIRS-SNPP) sensor and is obtained from the [Ocean Biology Processing Group](https://oceancolor.gsfc.nasa.gov/) at NASA's Goddard Space Flight Center.\n\n* Rrs_667 represents reflectance at 667nm and is a proxy for suspended sediments.\n\n* Algal Bloom Index (ABI) comes from the Moderate Resolution Spectroradiometer (MODIS-Aqua) and can be used to identify algal blooms. It is calculated using the method of Hu and Feng (2016; doi: 10.1117/1.JRS.11.012003) \n\n* River discharge data is obtained from the [USGS National Water Information System](https://waterdata.usgs.gov/nwis). Discharge values from the Shark, Broad, Lostmans and Chatham Rivers (green circles on map above) are summed to estimate discharge into the southern West Florida Shelf and plotted above. \n\n* In-situ temperature and salinity data is obtained from buoys maintained by the National Park Service and accessed through the [National Data Buoy Center](https://www.ndbc.noaa.gov/)\n\n* Dynamic seascapes are classified using multivariate satellite data and describe basin and gyre scale features and seasonal boundary shifts. They are obtained from [NOAA's Coastwatch](https://cwcgom.aoml.noaa.gov/erddap/griddap/noaa_aoml_seascapes_8day.graph). A description of seascape classes can be found [HERE](https://shiny.marinebon.app/seascapes/classes.html).\n\nPlease feel free to contact us with questions or to sign up for email alerts:\n\nDr. Daniel Otis - [dotis@usf.edu](mailto:dotis@usf.edu)\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "This work supported by",
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "![logo image](https://mbon-dashboards.marine.usf.edu/static_files/FKNMS_DBv24_Logo_Panel.png)"
   },
   "targets": [
    {}
   ]
  }
 ]
}