{
 "title": "Locations HUD",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Locations",
    "query": "BIS,UK,MUK,MK,LK,MQ,DT,WFB,EFB,WFS,SR,FKNMS"
   },
   {
    "name": "measurement",
    "query": "modis_abi,viirs_chlor_a,viirs_kd_490,viirs_rrs_671,viirs_sstn"
   }
  ]
 },
 "panels": [
  {
   "title": "Latest Region of Interest Last $measurement Anomaly",
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "LK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"anomaly\") FROM \"$measurement\"\nWHERE (\"location\" = 'LK') AND anomaly!=-999 fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"anomaly\") FROM \"$measurement\"\nWHERE (\"location\" = 'MK') AND anomaly!=-999 fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MUK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"anomaly\") FROM \"$measurement\"\nWHERE (\"location\" = 'MUK') AND anomaly!=-999 fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "UK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"anomaly\") FROM \"$measurement\"\nWHERE (\"location\" = 'UK') AND anomaly!=-999 fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "BIS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"anomaly\") FROM \"$measurement\"\nWHERE (\"location\" = 'BIS') AND anomaly!=-999 fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LK",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "viirs_chlor_a",
     "query": "SELECT mean(\"anomaly\") AS anomaly FROM \"$measurement\"\nWHERE (\"location\" = 'LK') AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MK",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "viirs_chlor_a",
     "query": "SELECT mean(\"anomaly\") AS anomaly FROM \"$measurement\"\nWHERE (\"location\" = 'MK') AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MUK",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "viirs_chlor_a",
     "query": "SELECT mean(\"anomaly\") AS anomaly FROM \"$measurement\"\nWHERE (\"location\" = 'MUK') AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UK",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "viirs_chlor_a",
     "query": "SELECT mean(\"anomaly\") AS anomaly FROM \"$measurement\"\nWHERE (\"location\" = 'UK') AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BIS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "viirs_chlor_a",
     "query": "SELECT mean(\"anomaly\") AS anomaly FROM \"$measurement\"\nWHERE (\"location\" = 'BIS') AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}