{
 "title": "Location Gauges",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Locations",
    "query": "BIS,UK,MUK,MK,LK,MQ,DT,WFB,EFB,WFS,SR,FKNMS"
   }
  ]
 },
 "panels": [
  {
   "title": "$Locations Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "repeat": "Locations",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "viirs_chlor_a",
     "query": "SELECT mean(\"mean\") AS anomaly FROM \"viirs_sstn\"\nWHERE (\"location\" =~ /^$Locations$/) AND mean!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Locations chlor a",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "repeat": "Locations",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "viirs_chlor_a",
     "query": "SELECT mean(\"mean\") AS anomaly FROM \"viirs_chlor_a\"\nWHERE (\"location\" =~ /^$Locations$/) AND mean!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Locations MODIS ABI",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "repeat": "Locations",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "viirs_chlor_a",
     "query": "SELECT mean(\"mean\") AS anomaly FROM \"modis_abi\"\nWHERE (\"location\" =~ /^$Locations$/) AND mean!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}