{
 "title": "FL_keys_dash",
 "tags": [
  "sanctuaries",
  "product_dash"
 ],
 "time": { "from": "2016-01-04T17:22:00.000Z", "to": "2016-08-07T19:22:00.000Z" },
 "templating": {
  "list": [
   { "name": "Locations", "query": "imars_regions.fk.roi.*" }
  ]
 },
 "panels": [
  { "title": "General information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "content": "![map of sub-regions](http://imars-webserver-01.marine.usf.edu/modis_aqua_fk/FKdb_map.png)"
  },
  {
   "title": "General information",
   "type": "text",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "content": "Select a specific location using the \"Locations\" dropdown menu at left.\n\nThe range of the displayed time period can be adjusted at top right.\n\nLocations of extracted data:\n* BB: Offshore Biscayne Bay\n* UK: Upper Keys\n* MR: Molasses Reef\n* SFP12: Station 12 from NOAA AOML's South Florida Program routine sampling\n* SFP18: Station 18 from NOAA AOML's South Florida Program routine sampling\n* WS: Western Sambo\n* LK: Looe Key\n* DT: Dry Tortugas\n* WFS: West Florida Shelf\n* SR: West of Shark River mouth \n* FLB: Florida Bay\n* IFB: Inner Florida Bay (SST only)\n\n\n"
  },
  { "title": "SST satellite images", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "MODIS-Aqua 7-Day SST anomaly images (DegC)",
   "type": "erddap-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Chlorophyll concentration satellite images",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "MODIS-Aqua CHLa 7-Day anomaly images (mg/m^3)",
     "type": "erddap-panel",
     "description": "MODIS-Aqua 1km chlor_a product (mg/m^3) binned to 7-day intervals.\nAnomaly images created by subtracting 7-day climatologies made using data from 2003-2017.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {}
     ]
    }
   ]
  },
  { "title": "Algal Bloom Index (ABI)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "MODIS-Aqua ABI 7-Day anomaly images (W/m^2/um/sr)",
   "type": "erddap-panel",
   "description": "via MODIS",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Normalized Fluorescence Line Height satellite images",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "MODIS-Aqua nFLH 7-Day anomaly images (W/m^2/um/sr)",
   "type": "erddap-panel",
   "description": "via MODIS",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rrs_667 (turbidity proxy) satellite images",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "MODIS-Aqua remote sensing reflectance at 667nm 7-Day anomaly images (sr^-1)",
   "type": "erddap-panel",
   "description": "via MODIS",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  { "title": "Satellite time-series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "SST @ $Locations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "DegC" }
   ],
   "targets": [
    {
     "target": "aliasByNode(imars_regions.fk.roi.$Locations.sst4.mean, 3)"
    }
   ]
  },
  {
   "title": "Chlorophyll-a @ $Locations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "mg/m^3" }
   ],
   "targets": [
    {
     "target": "aliasByNode(imars_regions.fk.roi.$Locations.chlor_a.mean, 3)"
    }
   ]
  },
  {
   "title": "Rrs_667 (turbidity proxy) @ $Locations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "sr^-1" }
   ],
   "targets": [
    {
     "target": "aliasByNode(imars_regions.fk.roi.$Locations.Rrs_667.mean, 3)"
    }
   ]
  },
  {
   "title": "nFLH @ $Locations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "W/m^2/um/sr" }
   ],
   "targets": [
    {
     "target": "aliasByNode(imars_regions.fk.roi.$Locations.nflh.mean, 3)"
    }
   ]
  },
  { "title": "Current conditions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "SST (DegC) @ $Locations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "imars_regions.fk.roi.$Locations.sst4.mean"
    }
   ]
  },
  {
   "title": "CHLa (mg/m^3) @ $Locations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "imars_regions.fk.roi.$Locations.chlor_a.mean"
    }
   ]
  },
  {
   "title": "Rrs_667 (turbidity proxy) @ $Locations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "imars_regions.fk.roi.$Locations.Rrs_667.mean"
    }
   ]
  },
  {
   "title": "nFLH @ $Locations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "imars_regions.fk.roi.$Locations.nflh.mean"
    }
   ]
  },
  {
   "title": "River Discharge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "River discharge into Florida Bay (combined discharge from gages shown as green circles on map)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short", "label": "m^3/sec" }
     ],
     "targets": [
      {
       "target": "aliasByNode(imars_regions.fk.river.FL_Bay_river_index, 3)"
      }
     ]
    }
   ]
  },
  { "title": "Buoy data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "In-situ salinity (psu) from Peterson Key buoy (yellow circle on map)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "PSU" }
   ],
   "targets": [
    {
     "target": "aliasByNode(imars_regions.fk.bouys.pkyf1.sal.{mean,climatology}, 3, 4, 5)"
    }
   ]
  },
  {
   "title": "In-situ temperature (DegC) at 0.5m from Peterson Key buoy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "DegC" }
   ],
   "targets": [
    {
     "target": "aliasByNode(imars_regions.fk.bouys.pkyf1.temp.{mean,climatology}, 3, 4, 5)"
    }
   ]
  },
  { "title": "Data sources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Data Sources and contact information",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
   "content": "* Satellite data is from the Moderate Resolution Imaging Spectroradiometer (MODIS-Aqua) sensor and is obtained from the [Ocean Biology Processing Group](https://oceancolor.gsfc.nasa.gov/) at NASA's Goddard Space Flight Center.\n\n* Algal Bloom Index (ABI) is calculated using the method of Hu and Feng (2016; doi: 10.1117/1.JRS.11.012003) \n\n* River discharge data is obtained from the [USGS National Water Information System](https://waterdata.usgs.gov/nwis). Discharge values from the Shark, Harney, Broad, Lostman's and Chatham Rivers (green circles on map above) are summed for discharge into Florida Bay shown on plot above.\n\n* Buoy at Peterson Key is operated by the National Park Service and data is obtained from the [National Data Buoy Center.](https://www.ndbc.noaa.gov/) \n\nPlease feel free to contact us with questions or to sign up for email alerts:\n\nDr. Daniel Otis - [dotis@mail.usf.edu](mailto:dotis@mail.usf.edu)\n\n"
  },
  { "title": "Acknowledgements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "This work supported by",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
   "content": "![logo image](http://imars-webserver-01.marine.usf.edu/modis_aqua_fk/FKdb_logos_horz.png)"
  }
 ]
}