{
 "title": "REACH Project Dashboard",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Locations",
    "label": "Satellite Time Series Extraction Locations",
    "query": "SHOW TAG VALUES FROM \"chlor_a\" WITH KEY = \"location\" WHERE \"region\" = 'REACH'"
   },
   { "name": "metric", "label": "Time Series Metric", "query": "SHOW FIELD KEYS from chlor_a" },
   {
    "name": "gauge_location",
    "query": "SHOW TAG VALUES FROM disch WITH KEY=location WHERE \"region\"='REACH'"
   }
  ]
 },
 "panels": [
  {
   "title": "REACH Project Map",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "url": "mbon-dashboards.marine.usf.edu/static_files/REACH_station_locations_vDB.csv",
     "url_options": { "body_content_type": "text/plain", "body_type": "raw", "data": "", "method": "GET" }
    },
    {
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "url": "mbon-dashboards.marine.usf.edu/static_files/REACH_surface_buoy_locations_vDB.csv",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "url": "mbon-dashboards.marine.usf.edu/static_files/REACH_buoy_locations_vDB.csv",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "mbon-dashboards.marine.usf.edu/static_files/Rice.geojson",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "url": "mbon-dashboards.marine.usf.edu/static_files/Labels_bathy.csv",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Welcome to the FIO-REACH Project data dashboard",
   "type": "text",
   "description": "This dashboard displays satellite data (as both images and time series) along with environmental data (river discharge).",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 0 },
   "options": {
    "content": "### Directions for site navigation \n\nFIO-REACH sampling locations are shown on map at left\n\nGreen circles = REACH Biological Sampling\n\nRed squares = OCG Subsurface Moorings\n\nYellow stars = OCG Surface Buoys\n\nRice's whale core habitat is represented by red polygon\n\nGray lines represent depth contours\n\nHover mouse over features on the map to see description\n\nSelect mean, climatology or anomaly using the \"Time Series Metric\" dropdown menu.\n\nThe range of the displayed time period can be adjusted at top right.\n\nTo view time series panels, simply click on the panel title (e.g. \"Satellite Imagery\" or \"Satellite Time Series Extractions\")\n\n\n\n\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Satellite Imagery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "VIIRS-SNPP CHLa 7-Day anomaly images (mg/m^3)",
     "type": "imars-grafanaerddap-panel",
     "description": "VIIRS-SNPP 750-m chlorophyll-a concentration (mg/m^3) binned to 7-day intervals. Anomaly images are created by subtracting a 7-day climatology using data from 2013-2019.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 }
    },
    {
     "title": "VIIRS-SNPP 7-Day nighttime SST anomaly images (DegC)",
     "type": "imars-grafanaerddap-panel",
     "description": "VIIRS-SNPP 750-m nighttime sea-surface temperature (DegC) binned to 7-day intervals. Anomaly images are created by subtracting a 7-day climatology using data from 2013-2019.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 }
    },
    {
     "title": "VIIRS-SNPP remote sensing reflectance at 671nm 7-Day anomaly images (sr^-1)",
     "type": "imars-grafanaerddap-panel",
     "description": "VIIRS-SNPP 750-m remote sensing reflectance (sr^-1) at 671nm binned to 7-day intervals. This is a proxy for suspended sediments at the surface. Anomaly images are created by subtracting a 7-day climatology using data from 2013-2019.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 }
    },
    {
     "title": "MODIS-Aqua Algal Bloom Index (ABI) 7-Day anomaly images (mW cm^-2 um^-1 sr^-1)",
     "type": "imars-grafanaerddap-panel",
     "description": "MODIS-Aqua 1-km Algal Bloom Index (mW cm^-2 um^-1 sr^-1) binned to 7-day intervals. This product can be used to identify algal blooms. Anomaly images are created by subtracting a 7-day climatology using data from 2003-2019.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 }
    },
    {
     "title": "Dynamic biogeographic seascapes (class)",
     "type": "imars-grafanaerddap-panel",
     "description": "Dynamic seascapes are classified using multivariate data and describe basin and gyre scale features and seasonal boundary shifts. A description of seascape classes can be found HERE.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 }
    }
   ]
  },
  {
   "title": "Satellite Time Series Extractions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "VSNPP Chlorophyll-a $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) as metric FROM \"chlor_a\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /VSNPP/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "VSNPP Nighttime SST $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"sstn\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /VSNPP/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "VIIRS Rrs 671 $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"Rrs_671\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /VSNPP/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "VIIRS Kd_490 $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"Kd_490\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /VSNPP/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "MODIS ABI $metric @ $Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"ABI\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /MODA/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "River Discharge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "USGS River Discharge from rivers draining into northeastern Gulf [m^3/s]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$tag_location $col",
       "query": "SELECT /^$metric$/ FROM disch\nWHERE (location =~ /^$gauge_location$/ AND $timeFilter)\nGROUP BY \"location\"\nfill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "COMPS Buoy Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "C24 & C23 Air Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "river_discharge",
       "query": "SELECT \"C23 Air temperature (deg C)\",\"C24 Air temperature (deg C)\"\nFROM \"comps_buoy\"\nWHERE $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "C24 & C23 Water Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "river_discharge",
       "query": "SELECT \"C23_INWATER Water Temperature (deg C) (1 m)\", \"C24_INWATER Water Temperature (deg C) (1 m)\"\nFROM \"comps_buoy\"\nWHERE $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Buoy Salinity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "river_discharge",
       "query": "SELECT \"C23_INWATER Salinity (PSU) (1 m)\",\"C24_INWATER Salinity (PSU) (1 m)\"\nFROM \"comps_buoy\"\nWHERE $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "More Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data Sources and Contact Information",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "* Satellite data (Chlorophyll-a, SST and Rrs_667) is from the Visible Infrared Imaging Spectrometer Suite (VIIRS-SNPP) sensor and is obtained from the [Ocean Biology Processing Group](https://oceancolor.gsfc.nasa.gov/) at NASA's Goddard Space Flight Center.\n\n* Rrs_667 represents reflectance at 667nm and is a proxy for suspended sediments.\n\n* Algal Bloom Index (ABI) comes from the Moderate Resolution Spectroradiometer (MODIS-Aqua) and can be used to identify algal blooms. It is calculated using the method of Hu and Feng (2016; doi: 10.1117/1.JRS.11.012003) \n\n* River discharge data is obtained from the [USGS National Water Information System](https://waterdata.usgs.gov/nwis). Discharge values from the Shark, Broad, Lostmans and Chatham Rivers (green circles on map above) are summed to estimate discharge into the southern West Florida Shelf and plotted above. \n\n* In-situ temperature and salinity data ...\n\n* Dynamic seascapes are classified using multivariate satellite data and describe basin and gyre scale features and seasonal boundary shifts. They are obtained from [NOAA's Coastwatch](https://cwcgom.aoml.noaa.gov/erddap/griddap/noaa_aoml_seascapes_8day.graph). A description of seascape classes can be found [HERE](https://shiny.marinebon.app/seascapes/classes.html).\n\nPlease feel free to contact us with questions or to sign up for email alerts:\n\nDr. Daniel Otis - [dotis@usf.edu](mailto:dotis@usf.edu)\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "More information (TODO: Update)",
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  }
 ]
}