{
 "title": "GRNMS Early Alert Dashboard",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Locations",
    "label": "Satellite Time Series Extraction Locations",
    "query": "SHOW TAG VALUES FROM \"chlor_a\" WITH KEY = \"location\" WHERE \"region\" = 'SEUS'"
   },
   { "name": "metric", "label": "Time Series Metric", "query": "SHOW FIELD KEYS FROM chlor_a" },
   {
    "name": "gauge_location",
    "label": "USGS River Gauge Location",
    "query": "SHOW TAG VALUES FROM gh WITH KEY=location WHERE \"region\"='SEUS'"
   },
   {
    "name": "NERR_Locations",
    "label": "NERR_Locations",
    "query": "SHOW TAG VALUES FROM nerrs WITH KEY=location"
   }
  ]
 },
 "panels": [
  {
   "title": "Location map and site navigation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 19, "w": 15, "x": 0, "y": 1 },
   "options": {
    "content": "![map of sub-regions](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-seus/static_files/SEUS_map_v4_wInset.png)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Welcome to the Gray's Reef NMS data dashboard",
   "type": "text",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 1 },
   "options": {
    "content": "### On the map above:\n\n - Black hatched circles indicate areas where satellite data is extracted. Select locations using the \"Satellite Time Series Extraction Locations\" dropdown at top left.\n \n - Green polygons (left) indicate NERRS locations, where nutrients and meteorological parameters are measured.\n\n - Red rectangle indicates the Gray's Reef National Marine Sanctuary boundary. \n \n - The black dot inside the sanctuary boundary indicates the location of NDBC Mooring 41008 where meteorological and ocean acidification parameters are measured.\n \n - \"12 nm\" and \"24 nm\" lines indicate the 12 nautical mile Territorial Sea and 24 nautical mile Contiguous Zone Maritime Boundaries. Data is from <a href=\"https://nauticalcharts.noaa.gov/data/us-maritime-limits-and-boundaries.html\" target=\"_blank\">NOAA's Office of Coast Survey</a>.\n\n### Directions for site navigation: \nClick the panel titles below to expand data panels.\n\nTo look at satellite time series, select location(s) using the the location number in the \"Satellite Time Series Extraction Locations\" dropdown menu at left.\n\nSelect mean, climatology or anomaly using the \"Time Series Metric\" dropdown menu.\n\nGauge height from the USGS is available from six locations (green dots on the map). Select river(s) to display using the \"USGS River Gauge Location\" dropdown menu.\n\nThe range of the displayed time period can be adjusted at top right.\n\n\n\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data Catalog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "List of Datasets and Acronyms",
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 41 },
     "options": {
      "content": "#### Data Catalog\n - Near real time (NRT) datasets are displayed on the dashboard as soon as they are available.  \n - Some datasets require manual downloading from deployed instruments and become available at irregular intervals once downloading and QC are complete.   \n - Some datasets consist of samples processed in a laboratory and become available at irregular intervals once processing and QC are complete.    \n\n\n###### A table of with the duration and frequency of each dataset displayed on the dashboard is shown below.  \n###### Further information on each dataset is shown at the top of the respective panel.  \n\n| Dataset                         | Start Date |  End Date  |  NRT?  | Frequency |      Notes                                 | \n| --------------------------------| ---------- |  --------  | ------ | --------- | ------------------------------------------ |\n| Satellite Images                | Jan 2012   |  Present   |  Yes   |  Weekly   |  Satellite data is from the VIIRS sensor*  | \n| Satellite Time Series           | Jan 2012   |  Present   |  Yes   |  Daily    |  Time series are extracted daily           |\n| NERRS WQ Data                   |            |            |  Yes   |  Hourly   |  Start date depends on NERR location       |\n| NERRS Nutrient Data             |            |            |  No    |  Monthy   |  Start date depends on NERR location       |\n| Meteorological and Wave Data    |            |            |  Yes   |  Hourly   |  Start date depends on NDBC buoy location  |\n| Ocean Acidification Data        |            |            |  No    |  Hourly   |                                            |\n\n*Algal Bloom Index (ABI) comes from the MODIS satellite sensor  \n\n### List of acronyms:\nABI - Algal Bloom Index  \nGRNMS - Gray's Reef National Marine Sanctuary  \nMODIS - Moderate Resolution Imaging Spectroradiometer (ocean color satellite)  \nNDBC - National Data Buoy Center  \nNERRS - National Estuarine Research Reserve System  \nNRT - Near real time  \nOA - Ocean Acidification  \nQC - Quality control  \nRRS - Remote Sensing Relfectance  \nSST - Sea Surface Temperature   \nVIIRS - Visible Infrared Imaging Spectrometer Suite (ocean color satellite)  \n\n\n\n\n\n\n\n\n\n\n"
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Satellite Imagery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Weekly chlorophyll anomalies (mg/m^3)",
     "type": "imars-grafanaerddap-panel",
     "description": "VIIRS-SNPP 750-m chlorophyll-a concentration (mg/m^3) binned to 7-day intervals.\nAnomaly images are created by subtracting a 7-day climatology using data from 2013-2019.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 }
    },
    {
     "title": "Weekly nighttime SST anomalies (DegC)",
     "type": "imars-grafanaerddap-panel",
     "description": "VIIRS-SNPP 750-m nighttime sea-surface temperature (DegC) binned to 7-day intervals.\nAnomaly images are created by subtracting a 7-day climatology using data from 2013-2019.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 }
    },
    {
     "title": "Weekly red reflectance (suspended sediment proxy) anomalies (sr^-1)",
     "type": "imars-grafanaerddap-panel",
     "description": "VIIRS-SNPP 750-m remote sensing reflectance (sr^-1) at 671nm binned to 7-day intervals. This is a proxy for suspended sediments at the surface.\nAnomaly images are created by subtracting a 7-day climatology using data from 2013-2019.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 }
    },
    {
     "title": "8-Day Biogeographic seascape classes",
     "type": "imars-grafanaerddap-panel",
     "description": "Dynamic seascapes are classified using multivariate  data and describe basin and gyre scale features and seasonal boundary shifts.  A description of seascape classes can be found [HERE](https://shiny.marinebon.app/seascapes/classes.html).",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 }
    }
   ]
  },
  {
   "title": "Satellite Imagery Time Series Extractions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "VIIRS Chlorophyll-a $metric @ location $Locations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) as metric FROM \"chlor_a\"\nWHERE (\"location\" =~ /^$Locations$/) AND (\"satellite\" =~ /VSNPP/)  AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "VIIRS Rrs 671 $metric @ location $Locations",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"Rrs_671\"\nWHERE (\"location\" =~ /^$Locations$/)  AND (\"satellite\" =~ /VSNPP/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "VIIRS Nighttime SST $metric @ location $Locations",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"sstn\"\nWHERE (\"location\" =~ /^$Locations$/)  AND (\"satellite\" =~ /VSNPP/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "VIIRS Kd_490 $metric @ location $Locations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"Kd_490\"\nWHERE (\"location\" =~ /^$Locations$/)  AND (\"satellite\" =~ /VSNPP/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    },
    {
     "title": "MODIS ABI $metric @ location $Locations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "modis_abi",
       "query": "SELECT mean(/^$metric$/) AS anomaly FROM \"ABI\"\nWHERE (\"location\" =~ /^$Locations$/)  AND (\"satellite\" =~ /MODA/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
       "select": [
        [
         { "params": [ "anomaly" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "NERRS Water Quality Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Data from National Estuarine Research Reserves System (NERRS)",
     "type": "text",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
     "options": {
      "content": "\n\n\n### NERRS water quality and nutrient data is from the Sapelo Island location:\nWater quality and nutrients are measured at four locations within the Sapelo Island NERR:\n1. Cabretta Creek\n2. Dean Creek\n3. Hunt Dock\n4. Lower Duplin\n\nPlease select locations(s) to visualize at the top.\n\n - Data are obtained from the NOAA National Estuarine Research Reserve System (NERRS) System-Wide Monitoring Program (SWMP). \n - Water quality and meteorological data are accessed nightly from the [NOAA NERRS Centralized Data Management Office website](http://www.nerrsdata.org) \n - Quality flags are applied to all NERRS SWMP data as described [HERE](https://cdmo.baruch.sc.edu/data/qaqc.cfm).\n - Nutrients are sampled monthly as part of routine monthly monitoring at each NERRS site. Data are made available once per year after a series of quality control checks.\n \n\n![logo image](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-seus/static_files/NERRS_logo_sm.jpg)\n\n\n\n\n\n"
     }
    },
    {
     "title": "Temperature @ $NERR_Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT ATemp as ATemp FROM \"nerrs\"\nWHERE (\"location\" =~ /^$NERR_Locations$/) AND $timeFilter \nGROUP BY \"location\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Dissolved Oxygen [mg/L] @ $NERR_Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT DO_mgl FROM \"nerrs\"\nWHERE (\"location\" =~ /^$NERR_Locations$/) AND $timeFilter \nGROUP BY \"location\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Turbidity @ $NERR_Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT Turb FROM \"nerrs\"\nWHERE (\"location\" =~ /^$NERR_Locations$/) AND $timeFilter \nGROUP BY \"location\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "pH @ $NERR_Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT pH FROM \"nerrs\"\nWHERE (\"location\" =~ /^$NERR_Locations$/) AND $timeFilter \nGROUP BY \"location\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Salinity @ $NERR_Locations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT Sal FROM \"nerrs\"\nWHERE (\"location\" =~ /^$NERR_Locations$/) AND $timeFilter \nGROUP BY \"location\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Meteorological and Wave Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Meterological and wave conditions within Gray's Reef NMS",
     "type": "text",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
     "options": {
      "content": "#### Station 41008 is a 3-m discus buoy located within Gray's Reef National Marine Sanctuary (31.40°N, 80.87°W). Water depth at this location is 16m.\n\n#### Meteorological parameters:\n1. Wind speed (m/s) averaged over an eight-minute period 3.8m above sea level.\n2. Wind direction (the direction the wind is coming from in degrees clockwise from true N) over an 8-minute period 3.8m above sea level. \n3. Peak 5 second gust speed (m/s) measured during the eight-minute or two-minute period 3.8m above sea level. \n4. Significant wave height (m) is the average of the highest one-third of all of the wave heights during the 20-minute sampling period.\n5. Air temperature (C) measured 3.4m above sea level.\n6. Water temperature (C) measured 2m below water line.\n7. Dominant wave period (seconds) is the period with the maximum wave energy.\n8. Average wave period (seconds) of all waves during the 20-minute period. \n9. Mean Wave Direction (MWD) - the direction from which the waves at the dominant period (DPD) are coming. The units are degrees from true North, (North = 0 (zero) degrees and East = 90 degrees.\n\nData is obtained from the [National Data Buoy Center](https://www.ndbc.noaa.gov/station_page.php?station=41008).\n\n\n\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Wind Speed (m/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "bouy_wspd",
       "query": "SELECT mean(\"wind_speed\") FROM \"meteorology\" \nWHERE $timeFilter \nGROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "data" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "\"data\"",
         "operator": "!=",
         "value": "-999"
        }
       ]
      }
     ]
    },
    {
     "title": "Wave Height (m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "bouy_wspd",
       "query": "SELECT mean(\"sea_surface_wave_significant_height\") FROM \"meteorology\" \nWHERE $timeFilter \nGROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "data" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "\"data\"",
         "operator": "!=",
         "value": "-999"
        }
       ]
      }
     ]
    },
    {
     "title": "Wind Gust (m/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "bouy_wspd",
       "query": "SELECT mean(\"wind_speed_of_gust\") FROM \"meteorology\" \nWHERE $timeFilter \nGROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "data" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "\"data\"",
         "operator": "!=",
         "value": "-999"
        }
       ]
      }
     ]
    },
    {
     "title": "Temperature (DegC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Sea Surface (met)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "bouy_wspd",
       "query": "SELECT mean(\"sea_surface_temperature\") FROM \"meteorology\" \nWHERE  $timeFilter \nGROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "data" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "\"data\"",
         "operator": "!=",
         "value": "-999"
        }
       ]
      },
      {
       "alias": "Air Temp (met)",
       "query": "SELECT mean(\"air_temperature\") FROM \"meteorology\" \nWHERE  $timeFilter \nGROUP BY time($__interval) fill(null)"
      }
     ]
    },
    {
     "title": "Mean Wave Period (sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "bouy_wspd",
       "query": "SELECT mean(\"sea_surface_wave_mean_period\") FROM \"meteorology\" \nWHERE $timeFilter \nGROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "data" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "\"data\"",
         "operator": "!=",
         "value": "-999"
        }
       ]
      }
     ]
    },
    {
     "title": "Dominant Wave Period (sec)",
     "type": "timeseries",
     "description": "sea_surface_wave_period_at_variance_spectral_density_maximum",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "bouy_wspd",
       "query": "SELECT mean(\"sea_surface_wave_period_at_variance_spectral_density_maximum\") FROM \"meteorology\" \nWHERE $timeFilter \nGROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "data" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "\"data\"",
         "operator": "!=",
         "value": "-999"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Ocean Acidification Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ocean Acidification parameters ",
     "type": "text",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
     "options": {
      "content": "\n## Ocean acidification parameters measured at the NDBC 41008 mooring (31.40°N, 80.87°W).\n\n####  - Data shown in this panel has undergone post-calibration and a full set of quality control checks and ends in 2019. Please adjust the time interval at top right to see data prior to 2019.\n####  - Recent data without full QC is available [HERE](https://www.pmel.noaa.gov/co2/story/Grays+Reef).\n\n - The National Data Buoy Center (NDBC) [Mooring 41008](https://www.ndbc.noaa.gov/station_page.php?station=41008) is located 40 nautical miles Southeast of Savannah, Georgia in Gray's Reef National Marine Sanctuary. \n - On July 17, 2006 PMEL in collaboration with NDBC and researchers from the University of Georgia deployed a MAPCO2TM system on the NDBC 41008 buoy. \n - Dr. Scott Noakes and Wei-Jun Cai are collaborating with us to maintain the system and have been deploying other sensors and making a variety of biogeochemical measurements in the Sanctuary. \n - For more information about complimentary projects at Gray's Reef visit the [Gray's Reef researcher's webpage](https://graysreef.noaa.gov/science/research/researchers/welcome.html).\n - On September 19, 2011, a surface seawater pH sensor was added to the Grays Reef mooring. By measuring pH in addition to pCO2, we are able to more accurately and precisely study the changes associated with ocean acidification. \n - This project is supported by [NOAA's Ocean Acidification Program](https://oceanacidification.noaa.gov/).\n\nParameters:\n1. Partial pressure of CO2 in air (micro atm).\n2. Partial pressure of CO2 in water (micro atm).\n3. Seawater salinity (psu).\n4. Seawater pH (unitless).\n5. Water temperature (degreesC).\n\n"
     },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "oa_params",
       "select": [
        [
         { "params": [ "pco2_in_air" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Partial pressure of CO2 in air (micro atm)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "oa_params",
       "query": "SELECT ApCo2 FROM oa_params ",
       "select": [
        [
         { "params": [ "pco2_in_air" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "partial pressure of CO2 in water (micro atm)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "oa_params",
       "query": "SELECT WpCo2 FROM \"oa_params\" ",
       "select": [
        [
         { "params": [ "pco2_in_sea_water" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Seawater pH (unitless)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "oa_params",
       "query": "SELECT pH FROM \"oa_params\" ",
       "select": [
        [
         {
          "params": [
           "sea_water_ph_reported_on_total_scale"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Seawater salinity (psu)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "oa_params",
       "query": "SELECT Sal FROM \"oa_params\" ",
       "select": [
        [
         { "params": [ "sea_water_practical_salinity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Water temperature (DegreesC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "oa_params",
       "query": "SELECT WTemp FROM \"oa_params\" ",
       "select": [
        [
         { "params": [ "sea_water_temperature" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "USGS River Gauge Height",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "USGS River Gauge Height (m)  $metric @ $gauge_location",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "river_discharge",
       "query": "SELECT /^$metric$/ FROM gh\nWHERE (location = '$gauge_location' AND $timeFilter )\nGROUP BY \"location\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "More Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Data Sources and Contact Information",
     "type": "text",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "options": {
      "content": "* Satellite data is from the Moderate Resolution Imaging Spectroradiometer (MODIS-Aqua) sensor and is obtained from the [Ocean Biology Processing Group](https://oceancolor.gsfc.nasa.gov/) at NASA's Goddard Space Flight Center.\n\n* Algal Bloom Index (ABI) is calculated using the method of [Hu and Feng 2016](https://www.spiedigitallibrary.org/journals/journal-of-applied-remote-sensing/volume-11/issue-01/012003/Modified-MODIS-fluorescence-line-height-data-product-to-improve-image/10.1117/1.JRS.11.012003.full?SSO=1)\n\n* River gauge height data (green cicles on map) are obtained from the [USGS National Water Information System](https://waterdata.usgs.gov/nwis).  \n\n* Dynamic seascapes are classified using multivariate satellite data and describe basin and gyre scale features and seasonal boundary shifts. They are obtained from [NOAA's Coastwatch](https://cwcgom.aoml.noaa.gov/erddap/griddap/noaa_aoml_seascapes_8day.graph). A description of seascape classes can be found [HERE](https://shiny.marinebon.app/seascapes/classes.html).\n\nPlease feel free to contact us with questions:\n\nDr. Daniel Otis - [dotis@usf.edu](mailto:dotis@usf.edu)\n\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "This work supported by",
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
     "options": {
      "content": "![logo image](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/client-seus/static_files/DB_logos_Horz_SEUS2.png)"
     },
     "targets": [
      {}
     ]
    }
   ]
  }
 ]
}